services:
  - type: web
    name: Auto-search-tamil-bot
    env: python
    runtime: python-3.10.8
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/TeamHMT/Auto-search-tamil-bot.git
    region: oregon
    plan: free
    branch: web
    numInstances: 1
    healthCheckPath: /
